version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{http://revtech2-frontend-beta.s3-website-us-east-1.amazonaws.com}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng add @angular/material --defaults --skip-confirmation
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes